### PR TITLE
Code style documentation

### LINKED ISSUE #1: JavaScript style guide
We should have some sort of JavaScript style guide for Cryb so we can make sure things stay consistent.

We could make our own ESLint configuration of sorts to use, or we could use Prettier and make our own configuration for that as well.

/cc @williamsthing would this be a good idea?

### PR DESCRIPTION
**Pull request by plusreed**
This will fix #1 when merged in.

- [x] Styling documentation
- [x] Configuration files
  - [x] ESLint
  - [x] `.editorconfig`

### CODE REVIEW

**Comment by jeda** [comment]
Added a `.editorconfig` which should work.

**Comment by plusreed** [comment]
Ready for review whenever you want @williamsthing

**Comment by plusreed** [comment]
@JeDaYoshi brought up a good point, the code styling doesn't mention anything about code like this:
```js
console.log(require('fs').readFileSync('logo.txt', 'utf-8')
			.replace('APERTURE_PORT', aperturePort)
			.replace('STREAMING_PORT', streamingPort)
)
```

@williamsthing What do you think we should do about this? Should we set a line length requirement?

**Comment by darnfish** [comment]
I'm not sure we should, but if we did what would be the limit?

**Comment by plusreed** [comment]
> I'm not sure we should, but if we did what would be the limit?

I'm not personally sure, but I feel like this would work fine:

In the event of a line like this: `functionCall().then().catch().finally()`, it should be spread out along multiple lines, like this:
```
functionCall()
	.then()
	.catch()
	.finally()
```

This would prevent super long lines. I'm open to hearing suggestions on this.

**Comment by plusreed** [comment]
@williamsthing sorry to keep poking you, but I just wanted your opinions on my suggestion above ^^

**Comment by williamsthing** [comment]
You will be sorry.

**Comment by darnfish** [comment]
That sounds good! @plusreed

**Comment by plusreed** [comment]
> That sounds good! @plusreed

I've written up some basic method chaining guidelines in https://github.com/crybapp/library/pull/2/commits/7f86ef707e0c59933c047a0616b4cbb642d1a20c. Would appreciate feedback from anyone!

**Comment by jeda** [comment]
Seems alright for me.

I just think the example could be changed to one that looks more like an example, like the one you mentioned. Can be fine to use this one anyway.

**Comment by plusreed** [comment]
> Seems alright for me.
> 
> I just think the example could be changed to one that looks more like an example, like the one you mentioned. Can be fine to use this one anyway.

How about this one? https://github.com/crybapp/library/commit/a431b7222bd99496cb55a6c3fdccb40a4c7090d0

**Comment by jeda** [comment]
Seems good!

**Pull request merged**
